### PR TITLE
Item management

### PR DESCRIPTION
**Pull request by smonfourny**
testing github action

### CODE REVIEW

**Comment by toshokan** [comment]
🎉

**Comment by smonfourny** [comment]
Kek @toshokan were you watching me tune my github action? Is this automated, I can't tell lmao

**Comment by toshokan** [comment]
@smonfourny I'm glad I don't have to wait for a `chore: .*` commit before testing a new merge :)

**Comment by smonfourny** [comment]
I've been having entirely too much fun with this haha

**Comment by toshokan** [comment]
Looks like it :)
Watching people work on their pet projects keeps me accountable toward my own

**Pull request merged**
